### ISSUE TITLE
Opaleye and Rel8 left joins

### ISSUE THREAD

**Issue by tomjaguarpaw** [Zelenya/elephants#1]
Thanks for this great initiative! I'm the Opaleye maintainer.  I wanted to summon Rel8 maintainer @ocharles here to check something about the Opaleye and Rel8 left join examples. For Rel8 we have

https://github.com/Zelenya/elephants/blob/f4903b41a2f99c5ec37f97fc972b37218f48e180/src/Elephants/Rel8.hs#L258

and this looks suspicious to me. @ocharles, if `pc` is `JustTable` but `categoriesForMapping` happened to return an empty `Query` then `c` would get bound to zero results but for a left join it should get bound to a single result of `NothingTable`, right?

Regarding the Opaleye example, and this is totally my fault for not providing more documentation around this, it is definitely wrong. Currently it is

https://github.com/Zelenya/elephants/blob/f4903b41a2f99c5ec37f97fc972b37218f48e180/src/Elephants/Opaleye.hs#L222-L230

but I'm pretty sure it should be

https://github.com/tomjaguarpaw/elephants/blob/2c14b66928f0b3512efb97ee48762c580ea011a5/src/Elephants/Opaleye.hs#L226-L235

as in https://github.com/tomjaguarpaw/elephants/commit/2c14b66928f0b3512efb97ee48762c580ea011a5. @ocharles, could you confirm whether that matches your understanding too?

If we can get this cleared up I'll submit a PR for the Opaleye version, and also try to improve the Opaleye documentation to explain this better.

**Comment by tomjaguarpaw** [comment]
At the very least I think we should extend [Rel8's doc on left joins](https://rel8.readthedocs.io/en/latest/cookbook.html#left-outer-joins) to explain what to do when we want to join on a `MaybeTable Expr`.

**Comment by ocharles** [comment]
Yea, I think you're correct @tomjaguarpaw. In CircuitHub's code base we have

```haskell
bindMaybeTable :: (a -> Query (MaybeTable Expr b)) -> MaybeTable Expr a -> Query (MaybeTable Expr b)
bindMaybeTable f ma = join <$> traverseMaybeTable f ma
```

which is used like so:

```haskell
  rack <-
    optional $ racksFromPanel panel

  rackInBay <-
    bindMaybeTable (optional . rackInBaysFromRack) rack
```

Interestingly we only use this combinator once in the entire codebase, so either we very seldom "extend" left joins, or we've forgotten that we have this!

**Comment by tomjaguarpaw** [comment]
Thanks @ocharles. I'm submitting an Opaleye correction at https://github.com/Zelenya/elephants/pull/2
